config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get 'search', to: 'search#index'
  post 'search', to: 'search#search'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks'}

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:me, :index] do
        get :me, on: :collection
        get :index, on: :collection
      end
      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        member { resources :answers, only: [:create] }
      end
      resources :answers, only: [:show, :update, :destroy]
    end
  end

  concern :votable do
    patch :add_points
    patch :low_points
  end

  concern :commentable do
    resources :commentable
  end

  resources :questions do
    get :subscribe
    get :unsubscribe
    resources :answers,
              shallow: true,
              only: [:create, :update, :destroy, :best] do
      post 'best'
      concerns :votable
      resources :comments, only: [:create]

    end
    concerns :votable
    resources :comments, only: [:create]

  end

  resources :attachments, only: [:purge_file] do
    delete :purge_file
  end

  resources :links, only: [:destroy]

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :best_answer, class_name: 'Answer'

  has_many :answers, dependent: :destroy
  has_many_attached :files

  has_many :links, dependent: :destroy, as: :linkable
  accepts_nested_attributes_for :links, reject_if: :all_blank

  validates :title, :body, presence: true

  has_one :reward, dependent: :destroy
  accepts_nested_attributes_for :reward, reject_if: :all_blank

  after_create :calculate_reputation, :create_subscription
  has_one :subscription, dependent: :destroy

  scope :questions_from_the_last_day, -> { where('created_at > ?', Date.today - 1.day) }

  def mark_as_best(answer)
    update(best_answer_id: answer.id)
  end

  def find_user
    User.find(author.id)
  end

  private

  def calculate_reputation
    ReputationJob.perform_later(self)
  end

  def create_subscription
    subscription = Subscription.create(question_id: id)
    save
    subscription.users.push(author)
  end
end

app/controllers/api/v1/questions_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class QuestionsController < Api::V1::BaseController
      before_action :find_question, only: %i[update destroy]

      def index
        @questions = Question.all
        render json: @questions
      end

      def show
        @question = Question.find(params[:id])
        render json: @question
      end

      def create
        authorize! :create, @question
        question = Question.new(title: params[:title], body: params[:body])
        if question.save
        end
        render json: @current_resource_owner
      end

      def update
        authorize! :create, @question
        @question.update(title: params[:title], body: params[:body])
        if @question.save
          render json: @question
        else
          errors_handler(@question)
        end
      end

      def destroy
        authorize! :create, @question
        render json: :success if @question.destroy
      end

      private

      def find_question
        @question = Question.with_attached_files.find(params[:id])
      end
    end
  end
end

app/controllers/questions_controller.rb
# frozen_string_literal: true

class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show edit update destroy]
  before_action :find_question, only: %i[subscribe unsubscribe]
  after_action :publish_question, only: [:create]

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer = Answer.new
    @best_answer = @question.best_answer
    @answer.links.build
    @other_answers = @question.answers.where.not(id: @question.best_answer_id)
  end

  def new
    @question = Question.new(author: current_user)
    @question&.links&.build
    @question.reward = Reward.new
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    @question.update(question_params)
    if @question.save
      redirect_to @question
    else
      render :edit
    end
  end

  def best
    @question.mark_as_best(answer)
  end

  def destroy
    @question.destroy if current_user.author_of?(@question)
    redirect_to questions_path
  end

  def subscribe
    @question.subscription.users.append(current_user)
    redirect_to @question, notice: 'Your subscription is running'
  end

  def unsubscribe
    @question.subscription.users.delete(current_user)
    redirect_to @question, notice: 'Your subscription is canceled'
  end

  private

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/short_question',
        locals: { q: @question }
      )
    )
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [], links_attributes: %i[name url])
  end
end

app/helpers/questions_helper.rb
# frozen_string_literal: true

module QuestionsHelper
end

app/views/questions/_form.html.slim
.question-errors
  =render 'shared/errors', resource: @question
= form_with model: @question, method: :patch, local: false  do |f|
  = f.label :body
  = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  = f.submit 'Update'

app/views/questions/_question.html.slim
.question
  h1= question.title
  - if current_user&.subscribed?(@question)
      p= link_to 'Unsubscribe', question_unsubscribe_path(@question)
  - else
      p= link_to 'Subscribe', question_subscribe_path(@question)
  p= question.body
  p= question.author.email
  .vote
    .points-up
      p= link_to image_tag('caret-up.svg'), question_add_points_path(question), remote: true, data: { data_action: 'up', method: :patch, type: :json }
    .points
      p= question.vote_points
    .points-down
      p= link_to image_tag('caret-down.svg'), question_low_points_path(question), remote: true, data: { data_action: 'up', method: :patch, type: :json }
  - if question.files.attached?
    - question.files.each do |file|
      p= link_to file.filename.to_s, url_for(file)
  - if current_user
    = form_with url: question_comments_path(question, commentable_type: Question, commentable_id: question.id), local: false do |c|
      = c.label :comment
      = c.text_field :comment
      = c.submit 'Comment!'

app/views/questions/_short_question.html.slim
p= link_to q.title, q

app/views/questions/edit.html.slim
- if can?(:update, current_user)
  = render 'questions/form'
  - if @question.files.attached?
    .files
      - @question.files.each do |file|
        div [id="file-#{file.id}"]
          p= link_to file.filename.to_s, url_for(file)
          p= link_to 'Delete file', attachment_purge_file_path(file), method: :delete, remote: true

app/views/questions/index.html.slim
p= link_to 'LOGIN', new_user_session_path
= render template: 'search/index'
-if can?(:create, Question)
  p= link_to 'Ask question', new_question_path
.questions
  h1= 'Questions list'
  - @questions.each do |q|
     p= link_to q.title, q

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question do |f|
  p
    = f.label :title
    = f.text_area :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  p Links:
  p
  #links
    = f.fields_for :links do |link|
      = render 'shared/link_fields', f: link
      = link_to_add_association 'add task', f, :links, partial: 'shared/link_fields'
  = render 'rewards/reward_fields', f: f
  p= f.submit 'Ask'

app/views/questions/show.html.slim
= render @question
.links
  p Links:
  ul
    - @question.links&.each do |link|
      li= link_to link.name, link.url
      li= link_to 'delete link', link_path(link), method: :delete, remote: true
      - if link.gist?
          <script src="#{link.url}.js"></script>
- if can? :edit, current_user, @question
  = link_to 'Edit question', edit_question_path(@question)
.answer-errors
  = render 'shared/errors', resource: @answer

- if current_user
  = render 'answers/form'
  - if @question.comments.any?
    = render 'comments/comments', model: @question

-  unless @best_answer.nil?
  .best-answer
    .border.border-danger
      p= 'Best Answer'
      = render @best_answer
div [id="answers-#{@question.id}"]
  = render @other_answers

app/views/questions/update.js.erb
<% if !@question.errors.present? %>
  $('#question-<%= @question.id %>').html('<%= j render @question %>');
<% end %>