config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

  get 'search', to: 'search#index'
  post 'search', to: 'search#search'

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks'}

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:me, :index] do
        get :me, on: :collection
        get :index, on: :collection
      end
      resources :questions, only: [:index, :show, :create, :update, :destroy] do
        member { resources :answers, only: [:create] }
      end
      resources :answers, only: [:show, :update, :destroy]
    end
  end

  concern :votable do
    patch :add_points
    patch :low_points
  end

  concern :commentable do
    resources :commentable
  end

  resources :questions do
    get :subscribe
    get :unsubscribe
    resources :answers,
              shallow: true,
              only: [:create, :update, :destroy, :best] do
      post 'best'
      concerns :votable
      resources :comments, only: [:create]

    end
    concerns :votable
    resources :comments, only: [:create]

  end

  resources :attachments, only: [:purge_file] do
    delete :purge_file
  end

  resources :links, only: [:destroy]

  root to: 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :question
  validates :body, presence: true
  has_many_attached :files

  has_many :links, dependent: :destroy, as: :linkable
  accepts_nested_attributes_for :links, reject_if: :all_blank

  def mark_as_best
    question.update(best_answer_id: id)
  end

  def best?
    !question.best_answer.nil? && question.best_answer.id == id
  end
end

app/controllers/answers_controller.rb
# frozen_string_literal: true

class AnswersController < ApplicationController
  include Voted

  before_action :load_question, only: %i[create]
  before_action :find_answer, only: %i[update destroy]
  before_action :load_answer, only: [:best]
  after_action :publish_answer, only: [:create]

  authorize_resource

  def create
    @answer = @question.answers.create(answer_params)
    @answer.author = current_user

    respond_to do |format|
      if @answer.save
        NotificationJob.perform_later(@answer)
        format.json { render json: @answer }
      else
        format.json { render json: @answer.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def update
    @answer.update(answer_params) if current_user.author_of?(@answer)
    @question = @answer.question
  end

  def destroy
    @answer.destroy if current_user.author_of?(@answer)
  end

  def best
    redirect_to @answer.question, notice: 'New best answer!' if @answer.mark_as_best
  end

  private

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "answers_for_q_#{@answer.question.id}",
      { body: ApplicationController.render(partial: 'answers/answer', locals: { answer: @answer, current_user: current_user }),
        question_id: @answer.question_id }
    )
  end

  def load_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end

  def load_answer
    @answer = Answer.find(params[:answer_id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[name url])
  end
end

app/controllers/api/v1/answers_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class AnswersController < Api::V1::BaseController
      before_action :find_question, only: [:create]
      before_action :find_answer, only: %i[update destroy]

      def show
        @answer = Answer.find(params[:id])
        render json: @answer
      end

      def create
        authorize! :create, @answer
        @answer = @question.answers.new(body: params[:body], user_id: current_resource_owner)
        if @answer.save
          render json: @answer
        else
          errors_handler(@answer)
        end
      end

      def update
        authorize! :create, @answer
        @answer.update(body: params[:body])
        if @answer.save
          render json: @answer
        else
          errors_handler(@answer)
        end
      end

      def destroy
        authorize! :create, @answer
        head :ok if @answer.destroy
      end

      private

      def find_question
        @question = Question.with_attached_files.find(params[:id])
      end

      def find_answer
        @answer = Answer.find(params[:id])
      end
    end
  end
end

app/helpers/answers_helper.rb
# frozen_string_literal: true

module AnswersHelper
end

app/views/answers/_answer.html.slim
div [id="answer-#{answer.id}"]
  .border.border-success
    p= answer.body
    - if answer.files.attached?
      - answer.files.each do |file|
        div [id="file-#{file.id}"]
          .border.border-primary
            p= link_to file.filename.to_s, url_for(file)
            p= link_to 'Delete file', attachment_purge_file_path(file), method: :delete, remote: true
    .vote
      .points-up
        p= link_to image_tag('caret-up.svg'), answer_add_points_path(answer, 'add_points'), remote: true, data: { data_action: 'up', method: :patch, type: :json }
      .points
        p= answer.vote_points
      .points-down
        p= link_to image_tag('caret-down.svg'), answer_low_points_path(answer), remote: true, data: { data_action: 'up', method: :patch, type: :json }
    .links
      p Links:
      ul
        - answer.links.each do |link|
          div [id="link-#{link.id}"]
            li= link_to link.name, link.url
            li= link_to 'delete link', link_path(link), method: :delete, remote: true
            - if link.gist?
              <script src="#{link.url}.js"></script>
    - if current_user

      = form_with url: answer_comments_path(answer, commentable_type: Answer, commentable_id: answer.id), local: false do |c|
        = c.label :comment
        = c.text_field :comment
        = c.submit 'Comment!'
      - if current_user.author_of?(answer)
        p= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
        p= link_to 'Delete answer', answer_path(answer), remote: true, method: :delete

      - if current_user.author_of?(answer.question) && !answer.best?
        p= button_to 'Mark as best', answer_best_path(answer.id)
    = form_with model: answer,
                method: :patch,
                html: { id: "edit-answer-#{answer.id}", class: 'hidden' }, local: false do |f|
      = f.label :body, 'Your answer'
      = f.text_field :body

      = f.label :files
      = f.file_field :files, multiple: true, direct_upload: true

      = f.submit 'Update'
  - if answer.comments.any?
    = render 'comments/comments', model: answer

app/views/answers/_best_answer.html.slim
p= @best_answer.body

app/views/answers/_form.html.slim
.answer-errors
  =render 'shared/errors', resource: @answer
  = form_with model: [@question, @answer], class: 'new-answer', local: false do |f|
    = f.label :body, 'Answer'
    = f.text_area :body, class: 'form-control'
    p Links:
    p
    #links
      = f.fields_for :links do |link|
        = render 'shared/link_fields', f: link
        = link_to_add_association 'add task', f, :links, partial: 'shared/link_fields'
    p
      = f.label :files, class: 'form-control'
      = f.file_field :files, multiple: true, direct_upload: true
    = f.submit 'Create', class: "btn btn-primary"

app/views/answers/best.js.erb
$('#answer-<%= @answer.id %>').html('<%= j render @best_answer %>');

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>')
  $('.new-answer')[0].reset()
<% end %>

app/views/answers/destroy.js.erb
$('#answer-<%= @answer.id %>').remove();

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% if !@answer.errors.present? %>
  $('#answer-<%= @answer.id %>').html('<%= j render @answer %>');
<% end %>